name: ci

on: [push]

jobs:
  test:
    name: Test
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-go@v1
      with:
        go-version: '1.13'
    - name: Build
      run: make build
    - name: Test
      run: make test
    - name: Full tests
      run: make testacc
